name: test

on:
  push:
    branches:    
      - main

jobs:
  gcloud:
    name: test-new-org-top-level
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Transferred to bharathkkb-test-org-2/github-actions but should still work. # renamed to bharathkkb-test-org-2/setup-gcloud # now it is top levelled 
  test-deploy-cloudrun:
    name: deploy-cloudrun-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master # Transferred to bharathkkb-test-org-2/github-actions but should still work. # renamed to bharathkkb-test-org-2/setup-gcloud #test another action
      with:
        image: gcr.io/cloudrun/hello
        service: hello-cloud-run
